import Head from 'next/head'
import { Navigation } from '../components'

export default function Home() {
  return (
    <>
      <Head>
        <title>
        COLABORACIÓN INSTITUCIONAL HOSPITAL INFANTIL DE MÉXICO-INSTITUTO NACIONAL DE PEDIATRíA
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Navigation />
      </>
    </>
  )
}
